sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zdx08080.
  wechat:
    appid: wxafc93b6565fd4601
    secret: 513055e5e18b317c3e1d894fd01a72fe
    notifyUrl: http://1199151e.r21.vip.cpolar.cn

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBc2F1536XzGNY2iETF
    access-key-secret: wq7mkhqJ2A2RXt9dOEMWyF1SmfyTvt
    bucket-name: sky-take-out-lianci

  redis:
    host: localhost
    port: 6379
    password: Zdx08080.

  shop:
    address: 福建省莆田市城厢区莆田学院

  baidu:
    ak: SVrWE653KCMtwnb8UwR39CSYMH5EK4Vq
